on:
  push:
    branches:
      - moster






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'testing Github action before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'testing Github action after'
        run: ls


      - name: 'login to docker hub'
        run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      - name: 'Building docker image'
        run: docker build -t ${{ secrets.USERNAME }}/myimage .

      - name: 'pushing to docker hub'
        run: docker push ${{ secrets.USERNAME }}/myimage
